# Generated by Django 3.1 on 2023-03-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
