# Generated by Django 3.1 on 2023-03-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230317_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_year_end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_year_start',
            field=models.IntegerField(),
        ),
    ]
