# Generated by Django 3.1 on 2023-03-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230317_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
